# Generated by Selenium IDE automated by Austin Jones 
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | https://www.walmart.com/ | 
    self.driver.get("https://www.walmart.com/")
    # 2 | click | css=.relative:nth-child(6) > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(6) > .flex").click()
    # 3 | click | css=.w_AU:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".w_AU:nth-child(2)").click()
    # 4 | type | id=first-name-su | Wally
    self.driver.find_element(By.ID, "first-name-su").send_keys("Wally")
    # 5 | type | id=last-name-su | Mart
    self.driver.find_element(By.ID, "last-name-su").send_keys("Mart")
    # 6 | type | id=email-su | amaxj95@gmail.com
    self.driver.find_element(By.ID, "email-su").send_keys("YOUREMAIL@EMAIL.COM")
    # 7 | type | id=password-su | walmartPass1
    self.driver.find_element(By.ID, "password-su").send_keys("walmartPass1")
    # 8 | click | css=div:nth-child(8) > .option > label | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(8) > .option > label").click()
    # 9 | click | css=#sign-up-form > .option > label | 
    self.driver.find_element(By.CSS_SELECTOR, "#sign-up-form > .option > label").click()
    # 10 | click | css=#sign-up-form > .button:nth-child(11) | 
    self.driver.find_element(By.CSS_SELECTOR, "#sign-up-form > .button:nth-child(11)").click()
    # 11 | close |  | 
    self.driver.close()
  
