// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:8080/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("https://www.walmart.com/");
    driver.findElement(By.cssSelector(".relative:nth-child(6) > .flex")).click();
    driver.findElement(By.cssSelector(".w_AI:nth-child(2)")).click();
    driver.findElement(By.id("first-name-su")).sendKeys("Wally");
    driver.findElement(By.id("last-name-su")).sendKeys("Mart");
    driver.findElement(By.id("email-su")).sendKeys("amaxj95@gmail.com");
    driver.findElement(By.id("password-su")).sendKeys("walmartPass1");
    driver.findElement(By.cssSelector("div:nth-child(8) > .option > label")).click();
    driver.findElement(By.cssSelector("#sign-up-form > .option > label")).click();
    driver.findElement(By.cssSelector("#sign-up-form > .button:nth-child(11)")).click();
    driver.close();
  }
}
